# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16c95f234ecf41b30e975415b7499ced9329259ed6479fae8498d53649a1df935dd6a0ec1e229273b6b10f47ed22fa3af5de8c4399ce04332ebbe5276036981f

test:
  secret_key_base: 058a7d6300d12352c0a9fe8bc93c8e6f756aa1c1ec624a9e969edc973c435821a6d38cd9a56af18c47e8758dff51584e57e16ca6b48ae42cdbb029c43b1334c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
